- id: cypher-linter
  name: Neo4J Cypher linter
  description: Neo4J Cypher linting via docker_image
  entry: cybergrx/cypher-linter:1.0.2
  language: docker_image
  files: \.(cypher|cql|cpy)$
- id: graphql-linter
  name: GraphQL schema linter
  description: GraphQL schema formatting and linting via docker_image
  entry: cybergrx/graphql-linter:1.0.1
  language: docker_image
  files: \.graphql$
- id: terraform-linter
  name: Terraform linter
  description: Terraform linting via docker_image
  entry: cybergrx/terraform-linter:1.0.1
  language: docker_image
  files: \.(tf|tfvars)$
- id: ts-project-linter
  name: Typescript project linter
  description: Typescript linting and prettier formatting for .ts and .tsx files via docker_image
  entry: cybergrx/ts-project-linter:1.0.7
  language: docker_image
  files: \.(ts|tsx)$
