repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-json
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
