- id: cypher-linter
  name: Neo4J Cypher linter
  description: Neo4J Cypher linting via docker_image
  entry: cybergrx/cypher-linter:latest
  language: docker_image
  files: \.(cypher|cql|cpy)$
- id: graphql-linter
  name: GraphQL schema linter
  description: GraphQL schema formatting and linting via docker_image
  entry: cybergrx/graphql-linter:latest
  language: docker_image
  files: \.graphql$
- id: terraform-linter
  name: Terraform linter
  description: Terraform linting via docker_image
  entry: cybergrx/terraform-linter:latest
  language: docker_image
  files: \.(tf|tfvars)$
