- id: cypher-linter
  name: Neo4J Cypher linter
  description: Neo4J Cypher linting via docker_image
  entry: cybergrx/cypher-linter:1.0.2
  language: docker_image
  files: \.(cypher|cql|cpy)$
- id: graphql-linter
  name: GraphQL schema linter
  description: GraphQL schema formatting and linting via docker_image
  entry: cybergrx/graphql-linter:1.0.1
  language: docker_image
  files: \.graphql$
- id: terraform-linter
  name: Terraform linter
  description: Terraform linting via docker_image
  entry: cybergrx/terraform-linter:1.0.1
  language: docker_image
  files: \.(tf|tfvars)$
- id: ts-project-linter
  name: Typescript project linter
  description: Typescript linting and prettier formatting for .ts and .tsx files via docker_image
  entry: cybergrx/ts-project-linter:1.0.7
  language: docker_image
  files: \.(ts|tsx)$
- id: golang-linter
  name: Golang file linter
  description: Golang linting via docker_image
  entry: cybergrx/golang-linter:1.0.0
  language: docker_image
  files: \.go$
- id: branch-length-checker
  name: Branch length checker
  description: Branch length checking via docker_image
  entry: cybergrx/branch-length-checker:1.0.0
  language: docker_image
  always_run: true
- id: kustomize-validator
  name: Kustomize build validator
  description: Builds kustomize packages
  entry: cybergrx/kustomize-validator:1.0.1
  language: docker_image
  files: ".y[a]{0,1}ml$"
- id: yaml-format
  name: Reformat yaml using yq
  description: Like gofmt but for yaml!
  entry: cybergrx/yaml-format:1.0.0
  language: docker_image
  files: ".y[a]{0,1}ml$"
